KUNST-72: The all in one go upgrade
itk-dev/kunstdatabasen pull request #68
Opened 2023-08-01 12:34 UTC by rimi-itk

2023-08-02 19:59 UTC, tuj requested changes

2023-08-02 19:59 UTC, tuj commented on .env
>  APP_SECRET=NotSoSecretReplace
APP_SECRET defined two times in the file

2023-08-02 19:59 UTC, tuj commented on README.md
> +docker compose run --rm node yarn build
and remove the node_modules folder

2023-08-02 19:59 UTC, tuj commented on migrations/Version20230801120357.php
> +        $this->addSql('DROP TABLE IF EXISTS migration_versions');
Why is this needed?

2023-08-03 10:48 UTC, rimi-itk commented on .env
>  APP_SECRET=NotSoSecretReplace
Fixed in https://github.com/itk-dev/kunstdatabasen/pull/68/commits/f734d8617b9accb1914b2ec4d9eff2c67f9b5c29.

2023-08-03 10:48 UTC, rimi-itk commented on README.md
> +docker compose run --rm node yarn build
Fixed in https://github.com/itk-dev/kunstdatabasen/pull/68/commits/84c646607fc9507b278089e70abe0c5bc243a2ba.

2023-08-03 11:00 UTC, rimi-itk commented on migrations/Version20230801120357.php
> +        $this->addSql('DROP TABLE IF EXISTS migration_versions');
I've updated the comment above the line with more details and a reference to https://github.com/doctrine/DoctrineMigrationsBundle/blob/3.2.x/UPGRADE.md#from-2x-to-300 (cf. https://github.com/itk-dev/kunstdatabasen/pull/68/commits/5a80bb354723625d0ca6482cd67f826ec3280a76).

How de we usually handle this situation? Do we add configuration to keep the `migration_versions` table name?

2023-08-04 08:29 UTC, tuj commented on migrations/Version20230801120357.php
> +        $this->addSql('DROP TABLE IF EXISTS migration_versions');
"and existing database" => "an existing database"

2023-08-04 08:29 UTC, tuj approved these changes

2023-08-10 13:48 UTC, merged